{
 "title": "Threat_Intelligence_OOREDOO Copy",
 "description": "Ce dashboard permet de visualiser : \nFichiers malveillants détectés par moteur d'analyse.\nIP suspectes par pays.\nTechniques d'attaque les plus fréquentes.",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Répartition des adresses IP analysées par pays",
   "type": "geomap",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "threat_intelligence",
     "rawSql": "SELECT \r\n    country AS country_code,\r\n    COUNT(ip_address) AS total_ips\r\nFROM \r\n    IpAnalysis\r\nGROUP BY \r\n    country;\r\n"
    }
   ]
  },
  {
   "title": "Top 10 Techniques d'Attaque",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "dataset": "threat_intelligence",
     "rawSql": "SELECT technique_code, COUNT(*) AS total_usage\r\nFROM AttackTechniques\r\nGROUP BY technique_code\r\nORDER BY total_usage DESC\r\nLIMIT 10;\r\n"
    }
   ]
  },
  {
   "title": "Proportion de chaque type d'IOC actif",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "threat_intelligence",
     "rawSql": "SELECT type, COUNT(*) AS total\r\nFROM PulseIndicators\r\nWHERE is_active = TRUE\r\nGROUP BY type;\r\n"
    }
   ]
  },
  {
   "title": "Nombre de rapports d'abus par plage d'adresses IP",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "dataset": "threat_intelligence",
     "rawSql": "SELECT network_address, COUNT(*) AS num_reports\r\nFROM AbuseIpReport\r\nJOIN ReportedIps ON AbuseIpReport.report_id = ReportedIps.report_id\r\nGROUP BY network_address;\r\n"
    }
   ]
  },
  {
   "title": "Top des adresses IP malveillantes les plus signalées",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "threat_intelligence",
     "rawSql": "SELECT ip_address, num_reports, abuse_confidence_score\r\nFROM ReportedIps\r\nORDER BY num_reports DESC, abuse_confidence_score DESC\r\nLIMIT 10;\r\n"
    }
   ]
  },
  {
   "title": "Techniques d'attaque pulse",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "dataset": "threat_intelligence",
     "rawSql": "SELECT Pulses.name AS pulse_name, GROUP_CONCAT(AttackTechniques.technique_code ORDER BY AttackTechniques.technique_code ASC) AS techniques_code_selon_mitre_attack\r\nFROM AttackTechniques\r\nJOIN Pulses ON AttackTechniques.pulse_key = Pulses.pulse_key\r\nGROUP BY Pulses.name;\r\n\r\n"
    }
   ]
  },
  {
   "title": "Nombre de fichiers malveillants détectés par moteur d'analyse ",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "dataset": "threat_intelligence",
     "rawSql": "SELECT engine_name_files, COUNT(*) AS total_detected \r\nFROM FileScans \r\nWHERE detected = TRUE \r\nGROUP BY engine_name_files;"
    }
   ]
  }
 ]
}